### ISSUE TITLE
FYI: Now available from AUR

### ISSUE THREAD

**Issue by kseistrup** [Sambigeara/fuzzynote#74]
Since there is no license, I hope it is ok with you that I have created a `fuzzynote` package in AUR:

* https://aur.archlinux.org/packages/fuzzynote/

ArchLinux users can now build and install `fuzzynote` with:

```sh
$ yay -S fuzzynote
```

**Comment by Sambigeara** [comment]
Thanks @kseistrup  - no problem at all, appreciate you sharing it.
