### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by mbos** [Sambigeara/fuzzynote#76]
It would be really nice if data could be exported. My ideal situation would be that the results of a search could be exported to a txt formatted file and that from the command line all the current entries could be exported.

**Comment by Sambigeara** [comment]
Hi @mbos! Thanks for taking the time. This is my interpretation of your request:

1. Search to generate result set
2. Enter some key combination to trigger "flush to file"
3. Result set gets written to some line separated file, e.g. `export_foo.txt`

Does that sound about right? This final part confused me a little:

> and that from the command line all the current entries could be exported.

Cheers.

**Comment by mbos** [comment]
Hey,

That sounds right. The second part would be:
use `fzn --export export_foo.txt` to get entire dataset

**Comment by Sambigeara** [comment]
Right, gotcha.

Agreed - will be some useful functionality 👍. Watch this space!

**Comment by Sambigeara** [comment]
For my own reference, consider an additional flag, e.g. `--visibility` or `--hide-items` etc to determine visibility when importing into fzn.

**Comment by Sambigeara** [comment]
In progress #79

**Comment by Sambigeara** [comment]
Aplogies for the delay on this one. I'm a little tied up at present but should have the time to wrap this up at the weekend (if not before)

**Comment by mbos** [comment]
Chill mate, I appreciate the pace and think the program has great potential but please there are lots more important things in life.

**Comment by Sambigeara** [comment]
Haha! Completely agree. Thanks dude 🙌

**Comment by Sambigeara** [comment]
Introduced support for this in [v0.21.0](https://github.com/Sambigeara/fuzzynote/releases/tag/v0.21.0)
[Usage](https://github.com/Sambigeara/fuzzynote#importexport)
