### ISSUE TITLE
Cannot build v0.25.0: »unrecognized import path “nhooyr.io/websocket”«

### ISSUE THREAD

**Issue by kseistrup** [Sambigeara/fuzzynote#96]
I wonder if this is just me:

I am unable to build `fuzzynote` v0.25.0 with `go` version go1.19.2 on linux/amd64: the hostname `nhooyr.io` does not resolve — not even if I ask the nameservers listed in whois (`ns{1,2}.hover.com`), and not even if I ask public resolvers like 1.1.1.1 or 8.8.8.8.

:thinking:

**Comment by Sambigeara** [comment]
Hmm. I shall try to recreate. Thanks for raising

**Comment by kseistrup** [comment]
I found the culprit (me): In order to _not_ having Evil Google track my IP address and log the instance each time I download a golang module, I had set the `GOPROXY=direct` environment variable. Everything worked as expected as soon as I unset `$GOPROXY`.

I'm sorry for having wasted your time.

**Comment by Sambigeara** [comment]
> I'm sorry for having wasted your time.

Not at all, I just learnt something new too 😬
